config/routes.rb
Rails.application.routes.draw do
  root "home#index"
  resources :home

  namespace :admin do
     resources :authors
     resources :apologizes
  end

end

app/models/apologize.rb
class Apologize < ActiveRecord::Base
  mount_uploader :apologize_image, ApologizeUploader
  belongs_to :author
end

app/models/author.rb
class Author < ActiveRecord::Base
  has_many :apologizes
end

app/controllers/admin/apologizes_controller.rb
class Admin::ApologizesController < ApplicationController
  before_action :set_apologize, only: [:show, :edit, :update, :destroy]
  before_action :set_authors, only: [:new, :edit]

  def index
    @apologizes = Apologize.all
  end


  def show
  end


  def new
    @apologize = Apologize.new
  end


  def edit
  end


  def create
    @apologize = Apologize.new(apologize_params)

      if @apologize.save
        redirect_to [:admin,@apologize], notice: 'Desculpa esfarrapada cadastrada com sucesso.'
      else
         render :new
      end
  end


  def update

      if @apologize.update(apologize_params)
        redirect_to [:admin,@apologize], notice: 'Desculpa esfarrapada cadastrada com sucesso.'
      else
        render :edit
      end
  end

  def destroy
    @apologize.destroy
    redirect_to admin_apologizes_url, notice: 'Deletado.'
  end

  private
    def set_authors
      @authors = Author.all.collect{|author| [author.name, author.id]}
    end

    def set_apologize
      @apologize = Apologize.find(params[:id])
    end


    def apologize_params
      params.require(:apologize).permit(:apologize_image, :description, :author_id)
    end
end

app/controllers/admin/authors_controller.rb
class Admin::AuthorsController < ApplicationController
  before_action :set_author, only: [:show, :edit, :update, :destroy]


  def index
    @authors = Author.all
  end


  def show
  end


  def new
    @author = Author.new
  end


  def edit
  end


  def create
    @author = Author.new(author_params)

      if @author.save
        redirect_to [:admin, @author], notice: 'Autor criado com sucesso.'
      else
        render :new
      end
  end


  def update
      if @author.update(author_params)
        redirect_to [:admin,@author], notice: 'Autor atualizado com sucesso'
      else
        render :edit
      end
  end


  def destroy
    @author.destroy
    redirect_to admin_authors_url, notice: 'Author was successfully destroyed.'
  end

  private

    def set_author
      @author = Author.find(params[:id])
    end


    def author_params
      params.require(:author).permit(:name)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
    @apologize = Apologize.order("RANDOM()").first
  end
end

app/helpers/apologizes_helper.rb
module ApologizesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/admin/apologizes/_form.html.erb
<%= form_for [:admin,@apologize] do |f| %>
  <% if @apologize.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@apologize.errors.count, "error") %> prohibited this apologize from being saved:</h2>

      <ul>
      <% @apologize.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :apologize_image %><br>
    <%= f.file_field :apologize_image%>
  </div>
  <div class="field">
    <%= f.label :description %><br>
    <%= f.text_area :description , class:"form-control"  %>
  </div>
  <div class="field">
    <%= f.label :author_id %><br>
    <%= f.select :author_id , @authors, {prompt: "selecione"}, class:"form-control"  %>
  </div>
  <br>
  <div class="actions">
    <%= f.submit "salvar", class:"btn btn-primary btn-xs" %>
  </div>
<% end %>

app/views/admin/apologizes/edit.html.erb
<h1>Editing Apologize</h1>

<div class="jumbotron">
  <%= render 'form' %>
</div>

<%= link_to 'exibir', [:admin, @apologize] %> |
<%= link_to 'voltar', admin_apologizes_path %>

app/views/admin/apologizes/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Desculpas para não sair</h1>
<div data-toggle="tooltip"  title="Cadastrar desculpa">
  <%= link_to '+ Desculpa', new_admin_apologize_path, class:"btn btn-primary pull-right btn-sm" %>
</div>

<table class="table table-hover">
  <thead>
    <tr>
      <th>Imagem</th>
      <th>Desculpa</th>
      <th>Autor</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @apologizes.each do |apologize| %>
      <tr>
        <td><%= image_tag(apologize.apologize_image, size:"90x90") %></td>
        <td><%= apologize.description %></td>
        <td><%= apologize.author.try(:name) %></td>
          <td>
            <div class="btn-group" role="group" aria-label="...">
              <%= link_to 'Show', [:admin,apologize], class:"btn btn-info btn-xs" %>
              <%= link_to 'Edit', edit_admin_apologize_path(apologize), class:"btn btn-info btn-xs" %>
              <%= link_to 'Destroy', [:admin,apologize], method: :delete, data: { confirm: 'Are you sure?' }, class:"btn btn-danger btn-xs" %>
              </div>
          </td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/admin/apologizes/new.html.erb
<h1>Nova desculpa</h1>
<div class="jumbotron">
  <%= render 'form' %>
</div>

<%= link_to 'voltar', admin_apologizes_path %>

app/views/admin/apologizes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Apologize image:</strong>
  <%= image_tag(@apologize.apologize_image,size: "100x100") %>
</p>

<p>
  <strong>Description:</strong>
  <%= @apologize.description %>
</p>

<p>
  <strong>Author:</strong>
  <%= @apologize.author.try(:name) %>
</p>

<%= link_to 'Edit', edit_admin_apologize_path(@apologize) %> |
<%= link_to 'Back', admin_apologizes_path %>

app/views/admin/authors/_form.html.erb
<%= form_for [:admin, @author] do |f| %>
  <% if @author.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@author.errors.count, "error") %> prohibited this author from being saved:</h2>

      <ul>
      <% @author.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/admin/authors/edit.html.erb
<h1>Editing Author</h1>

<%= render 'form' %>

<%= link_to 'Show', [:admin,@author] %> |
<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Authors</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @authors.each do |author| %>
      <tr>
        <td><%= author.name %></td>
        <td><%= link_to 'Show', [:admin,author] %></td>
        <td><%= link_to 'Edit', edit_admin_author_path(author) %></td>
        <td><%= link_to 'Destroy', [:admin,author], method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Author', new_admin_author_path %>

app/views/admin/authors/new.html.erb
<h1>New Author</h1>

<%= render 'form' %>

<%= link_to 'Back', admin_authors_path %>

app/views/admin/authors/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @author.name %>
</p>

<%= link_to 'Edit', edit_admin_author_path(@author) %> |
<%= link_to 'Back', admin_authors_path %>

app/views/home/index.html.erb
<div class="col-sm-12">
  <div class="col-sm-offset-2">
    <h2>Gerador de desculpas para não sair de casa</h2>
    <h5>Se você não aguenta mais pensar em desculpas para não sair fds, essa ferramenta é pra você</h5>
  </div>
  <center>
    <%= image_tag(@apologize.apologize_image , size: "500x300") %>
  </center>
  <div class="col-sm-8 col-sm-offset-2 jumbotron">
     <div class="container">
        <%= @apologize.description %>
      </div>
  </div>
</div>


<div class="col-sm-offset-3 col-sm-5">
  <%= link_to "gerar desculpa", home_index_path, method: :get, class:"btn btn-danger btn-block" %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>GeradorDeDesculpasApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <div class="container">
    <% unless current_page?(home_index_path)  %>
      <ul class="nav nav-pills">
        <li role="presentation"><%= link_to "Desculpas" , admin_apologizes_path %></li>
        <li role="presentation"><%= link_to "Autores" , admin_authors_path %></li>
      </ul>
    <% end %>
    <%= yield %>
  </div>

</body>
</html>